package com.example.hauptstadtraten

object CountryData {
    val countries = listOf(
        Country("Afghanistan", "Kabul", listOf("Kaboul"), "🇦🇫", "Asia"),
        Country("Albania", "Tirana", listOf("Tiranë", "Tiran"), "🇦🇱", "Europe"),
        Country("Algeria", "Algiers", listOf("Algier", "Alger"), "🇩🇿", "Africa"),
        Country("Andorra", "Andorra la Vella", listOf("Andorra"), "🇦🇩", "Europe"),
        Country("Angola", "Luanda", emptyList(), "🇦🇴", "Africa"),
        Country("Antigua and Barbuda", "Saint John's", listOf("St. John's", "St John's"), "🇦🇬", "North America"),
        Country("Argentina", "Buenos Aires", listOf("Buënos Aires"), "🇦🇷", "South America"),
        Country("Armenia", "Yerevan", listOf("Eriwan", "Jerewan"), "🇦🇲", "Asia"),
        Country("Australia", "Canberra", emptyList(), "🇦🇺", "Oceania"),
        Country("Austria", "Vienna", listOf("Wien"), "🇦🇹", "Europe"),
        Country("Azerbaijan", "Baku", listOf("Baki"), "🇦🇿", "Asia"),
        Country("Bahamas", "Nassau", emptyList(), "🇧🇸", "North America"),
        Country("Bahrain", "Manama", listOf("Al-Manama"), "🇧🇭", "Asia"),
        Country("Bangladesh", "Dhaka", listOf("Dakka"), "🇧🇩", "Asia"),
        Country("Barbados", "Bridgetown", emptyList(), "🇧🇧", "North America"),
        Country("Belarus", "Minsk", emptyList(), "🇧🇾", "Europe"),
        Country("Belgium", "Brussels", listOf("Brüssel", "Bruxelles"), "🇧🇪", "Europe"),
        Country("Belize", "Belmopan", emptyList(), "🇧🇿", "North America"),
        Country("Benin", "Porto-Novo", listOf("Porto Novo"), "🇧🇯", "Africa"),
        Country("Bhutan", "Thimphu", listOf("Thimbu"), "🇧🇹", "Asia"),
        Country("Bolivia", "Sucre", listOf("La Paz"), "🇧🇴", "South America"),
        Country("Bosnia and Herzegovina", "Sarajevo", listOf("Sarajewo"), "🇧🇦", "Europe"),
        Country("Botswana", "Gaborone", emptyList(), "🇧🇼", "Africa"),
        Country("Brazil", "Brasília", listOf("Brasilia"), "🇧🇷", "South America"),
        Country("Brunei", "Bandar Seri Begawan", listOf("BSB"), "🇧🇳", "Asia"),
        Country("Bulgaria", "Sofia", listOf("Sofija"), "🇧🇬", "Europe"),
        Country("Burkina Faso", "Ouagadougou", listOf("Wagadugu"), "🇧🇫", "Africa"),
        Country("Burundi", "Gitega", listOf("Bujumbura"), "🇧🇮", "Africa"),
        Country("Cabo Verde", "Praia", emptyList(), "🇨🇻", "Africa"),
        Country("Cambodia", "Phnom Penh", listOf("Pnom Penh"), "🇰🇭", "Asia"),
        Country("Cameroon", "Yaoundé", listOf("Yaounde", "Jaunde"), "🇨🇲", "Africa"),
        Country("Canada", "Ottawa", emptyList(), "🇨🇦", "North America"),
        Country("Central African Republic", "Bangui", emptyList(), "🇨🇫", "Africa"),
        Country("Chad", "N'Djamena", listOf("NDjamena", "Ndjamena"), "🇹🇩", "Africa"),
        Country("Chile", "Santiago", listOf("Santiago de Chile"), "🇨🇱", "South America"),
        Country("China", "Beijing", listOf("Peking"), "🇨🇳", "Asia"),
        Country("Colombia", "Bogotá", listOf("Bogota", "Santa Fe de Bogotá"), "🇨🇴", "South America"),
        Country("Comoros", "Moroni", emptyList(), "🇰🇲", "Africa"),
        Country("Congo, Democratic Republic", "Kinshasa", emptyList(), "🇨🇩", "Africa"),
        Country("Congo, Republic", "Brazzaville", emptyList(), "🇨🇬", "Africa"),
        Country("Costa Rica", "San José", listOf("San Jose"), "🇨🇷", "North America"),
        Country("Croatia", "Zagreb", emptyList(), "🇭🇷", "Europe"),
        Country("Cuba", "Havana", listOf("Havanna", "La Habana"), "🇨🇺", "North America"),
        Country("Cyprus", "Nicosia", listOf("Nikosía", "Lefkoşa"), "🇨🇾", "Europe"),
        Country("Czechia", "Prague", listOf("Prag", "Praha"), "🇨🇿", "Europe"),
        Country("Denmark", "Copenhagen", listOf("Kopenhagen", "København"), "🇩🇰", "Europe"),
        Country("Djibouti", "Djibouti", listOf("Dschibuti"), "🇩🇯", "Africa"),
        Country("Dominica", "Roseau", emptyList(), "🇩🇲", "North America"),
        Country("Dominican Republic", "Santo Domingo", emptyList(), "🇩🇴", "North America"),
        Country("Ecuador", "Quito", emptyList(), "🇪🇨", "South America"),
        Country("Egypt", "Cairo", listOf("Kairo", "Al-Qahira"), "🇪🇬", "Africa"),
        Country("El Salvador", "San Salvador", emptyList(), "🇸🇻", "North America"),
        Country("Equatorial Guinea", "Malabo", emptyList(), "🇬🇶", "Africa"),
        Country("Eritrea", "Asmara", emptyList(), "🇪🇷", "Africa"),
        Country("Estonia", "Tallinn", emptyList(), "🇪🇪", "Europe"),
        Country("Eswatini", "Mbabane", emptyList(), "🇸🇿", "Africa"),
        Country("Ethiopia", "Addis Ababa", listOf("Addis Abeba"), "🇪🇹", "Africa"),
        Country("Fiji", "Suva", emptyList(), "🇫🇯", "Oceania"),
        Country("Finland", "Helsinki", emptyList(), "🇫🇮", "Europe"),
        Country("France", "Paris", emptyList(), "🇫🇷", "Europe"),
        Country("Gabon", "Libreville", emptyList(), "🇬🇦", "Africa"),
        Country("Gambia", "Banjul", emptyList(), "🇬🇲", "Africa"),
        Country("Georgia", "Tbilisi", listOf("Tiflis"), "🇬🇪", "Asia"),
        Country("Germany", "Berlin", emptyList(), "🇩🇪", "Europe"),
        Country("Ghana", "Accra", emptyList(), "🇬🇭", "Africa"),
        Country("Greece", "Athens", listOf("Athen", "Athina"), "🇬🇷", "Europe"),
        Country("Grenada", "St. George's", listOf("Saint George's"), "🇬🇩", "North America"),
        Country("Guatemala", "Guatemala City", listOf("Guatemala-Stadt", "Guatemala"), "🇬🇹", "North America"),
        Country("Guinea", "Conakry", emptyList(), "🇬🇳", "Africa"),
        Country("Guinea-Bissau", "Bissau", emptyList(), "🇬🇼", "Africa"),
        Country("Guyana", "Georgetown", emptyList(), "🇬🇾", "South America"),
        Country("Haiti", "Port-au-Prince", listOf("Port au Prince"), "🇭🇹", "North America"),
        Country("Honduras", "Tegucigalpa", emptyList(), "🇭🇳", "North America"),
        Country("Hungary", "Budapest", emptyList(), "🇭🇺", "Europe"),
        Country("Iceland", "Reykjavik", listOf("Reykjavík"), "🇮🇸", "Europe"),
        Country("India", "New Delhi", listOf("Neu-Delhi", "Delhi"), "🇮🇳", "Asia"),
        Country("Indonesia", "Jakarta", listOf("Djakarta"), "🇮🇩", "Asia"),
        Country("Iran", "Tehran", listOf("Teheran"), "🇮🇷", "Asia"),
        Country("Iraq", "Baghdad", listOf("Bagdad"), "🇮🇶", "Asia"),
        Country("Ireland", "Dublin", emptyList(), "🇮🇪", "Europe"),
        Country("Israel", "Jerusalem", listOf("Jeruzalem", "Yerushalayim"), "🇮🇱", "Asia"),
        Country("Italy", "Rome", listOf("Rom", "Roma"), "🇮🇹", "Europe"),
        Country("Jamaica", "Kingston", emptyList(), "🇯🇲", "North America"),
        Country("Japan", "Tokyo", listOf("Tokio"), "🇯🇵", "Asia"),
        Country("Jordan", "Amman", emptyList(), "🇯🇴", "Asia"),
        Country("Kazakhstan", "Astana", listOf("Nur-Sultan"), "🇰🇿", "Asia"),
        Country("Kenya", "Nairobi", emptyList(), "🇰🇪", "Africa"),
        Country("Kiribati", "Tarawa", listOf("South Tarawa"), "🇰🇮", "Oceania"),
        Country("Korea, North", "Pyongyang", listOf("Pjöngjang"), "🇰🇵", "Asia"),
        Country("Korea, South", "Seoul", emptyList(), "🇰🇷", "Asia"),
        Country("Kosovo", "Pristina", listOf("Prishtina", "Priština"), "🇽🇰", "Europe"),
        Country("Kuwait", "Kuwait City", listOf("Kuwait-Stadt", "Kuwait"), "🇰🇼", "Asia"),
        Country("Kyrgyzstan", "Bishkek", listOf("Bischkek"), "🇰🇬", "Asia"),
        Country("Laos", "Vientiane", emptyList(), "🇱🇦", "Asia"),
        Country("Latvia", "Riga", emptyList(), "🇱🇻", "Europe"),
        Country("Lebanon", "Beirut", listOf("Beyrouth"), "🇱🇧", "Asia"),
        Country("Lesotho", "Maseru", emptyList(), "🇱🇸", "Africa"),
        Country("Liberia", "Monrovia", emptyList(), "🇱🇷", "Africa"),
        Country("Libya", "Tripoli", listOf("Tripolis"), "🇱🇾", "Africa"),
        Country("Liechtenstein", "Vaduz", emptyList(), "🇱🇮", "Europe"),
        Country("Lithuania", "Vilnius", listOf("Wilna"), "🇱🇹", "Europe"),
        Country("Luxembourg", "Luxembourg", listOf("Luxemburg"), "🇱🇺", "Europe"),
        Country("Madagascar", "Antananarivo", emptyList(), "🇲🇬", "Africa"),
        Country("Malawi", "Lilongwe", emptyList(), "🇲🇼", "Africa"),
        Country("Malaysia", "Kuala Lumpur", emptyList(), "🇲🇾", "Asia"),
        Country("Maldives", "Malé", listOf("Male"), "🇲🇻", "Asia"),
        Country("Mali", "Bamako", emptyList(), "🇲🇱", "Africa"),
        Country("Malta", "Valletta", emptyList(), "🇲🇹", "Europe"),
        Country("Marshall Islands", "Majuro", emptyList(), "🇲🇭", "Oceania"),
        Country("Mauritania", "Nouakchott", emptyList(), "🇲🇷", "Africa"),
        Country("Mauritius", "Port Louis", emptyList(), "🇲🇺", "Africa"),
        Country("Mexico", "Mexico City", listOf("Mexiko-Stadt", "Ciudad de México"), "🇲🇽", "North America"),
        Country("Micronesia", "Palikir", emptyList(), "🇫🇲", "Oceania"),
        Country("Moldova", "Chisinau", listOf("Chişinău", "Kischinau"), "🇲🇩", "Europe"),
        Country("Monaco", "Monaco", listOf("Monte Carlo"), "🇲🇨", "Europe"),
        Country("Mongolia", "Ulaanbaatar", listOf("Ulan Bator"), "🇲🇳", "Asia"),
        Country("Montenegro", "Podgorica", emptyList(), "🇲🇪", "Europe"),
        Country("Morocco", "Rabat", emptyList(), "🇲🇦", "Africa"),
        Country("Mozambique", "Maputo", emptyList(), "🇲🇿", "Africa"),
        Country("Myanmar", "Naypyidaw", listOf("Nay Pyi Taw"), "🇲🇲", "Asia"),
        Country("Namibia", "Windhoek", listOf("Windhuk"), "🇳🇦", "Africa"),
        Country("Nauru", "Yaren", emptyList(), "🇳🇷", "Oceania"),
        Country("Nepal", "Kathmandu", listOf("Katmandu"), "🇳🇵", "Asia"),
        Country("Netherlands", "Amsterdam", emptyList(), "🇳🇱", "Europe"),
        Country("New Zealand", "Wellington", emptyList(), "🇳🇿", "Oceania"),
        Country("Nicaragua", "Managua", emptyList(), "🇳🇮", "North America"),
        Country("Niger", "Niamey", emptyList(), "🇳🇪", "Africa"),
        Country("Nigeria", "Abuja", emptyList(), "🇳🇬", "Africa"),
        Country("North Macedonia", "Skopje", emptyList(), "🇲🇰", "Europe"),
        Country("Norway", "Oslo", emptyList(), "🇳🇴", "Europe"),
        Country("Oman", "Muscat", listOf("Maskat"), "🇴🇲", "Asia"),
        Country("Pakistan", "Islamabad", emptyList(), "🇵🇰", "Asia"),
        Country("Palau", "Ngerulmud", emptyList(), "🇵🇼", "Oceania"),
        Country("Palestine", "Ramallah", emptyList(), "🇵🇸", "Asia"),
        Country("Panama", "Panama City", listOf("Panama-Stadt", "Panama"), "🇵🇦", "North America"),
        Country("Papua New Guinea", "Port Moresby", emptyList(), "🇵🇬", "Oceania"),
        Country("Paraguay", "Asunción", listOf("Asuncion"), "🇵🇾", "South America"),
        Country("Peru", "Lima", emptyList(), "🇵🇪", "South America"),
        Country("Philippines", "Manila", emptyList(), "🇵🇭", "Asia"),
        Country("Poland", "Warsaw", listOf("Warschau", "Warszawa"), "🇵🇱", "Europe"),
        Country("Portugal", "Lisbon", listOf("Lissabon", "Lisboa"), "🇵🇹", "Europe"),
        Country("Qatar", "Doha", emptyList(), "🇶🇦", "Asia"),
        Country("Romania", "Bucharest", listOf("Bukarest", "București"), "🇷🇴", "Europe"),
        Country("Russia", "Moscow", listOf("Moskau", "Moskva"), "🇷🇺", "Europe"),
        Country("Rwanda", "Kigali", emptyList(), "🇷🇼", "Africa"),
        Country("Saint Kitts and Nevis", "Basseterre", emptyList(), "🇰🇳", "North America"),
        Country("Saint Lucia", "Castries", emptyList(), "🇱🇨", "North America"),
        Country("Saint Vincent and the Grenadines", "Kingstown", emptyList(), "🇻🇨", "North America"),
        Country("Samoa", "Apia", emptyList(), "🇼🇸", "Oceania"),
        Country("San Marino", "San Marino", emptyList(), "🇸🇲", "Europe"),
        Country("Sao Tome and Principe", "São Tomé", listOf("Sao Tome"), "🇸🇹", "Africa"),
        Country("Saudi Arabia", "Riyadh", listOf("Riad"), "🇸🇦", "Asia"),
        Country("Senegal", "Dakar", emptyList(), "🇸🇳", "Africa"),
        Country("Serbia", "Belgrade", listOf("Belgrad", "Beograd"), "🇷🇸", "Europe"),
        Country("Seychelles", "Victoria", emptyList(), "🇸🇨", "Africa"),
        Country("Sierra Leone", "Freetown", emptyList(), "🇸🇱", "Africa"),
        Country("Singapore", "Singapore", listOf("Singapur"), "🇸🇬", "Asia"),
        Country("Slovakia", "Bratislava", listOf("Pressburg"), "🇸🇰", "Europe"),
        Country("Slovenia", "Ljubljana", listOf("Laibach"), "🇸🇮", "Europe"),
        Country("Solomon Islands", "Honiara", emptyList(), "🇸🇧", "Oceania"),
        Country("Somalia", "Mogadishu", listOf("Mogadischu"), "🇸🇴", "Africa"),
        Country("South Africa", "Pretoria", listOf("Kapstadt", "Cape Town", "Bloemfontein"), "🇿🇦", "Africa"),
        Country("South Sudan", "Juba", emptyList(), "🇸🇸", "Africa"),
        Country("Spain", "Madrid", emptyList(), "🇪🇸", "Europe"),
        Country("Sri Lanka", "Sri Jayawardenepura Kotte", listOf("Kotte", "Colombo"), "🇱🇰", "Asia"),
        Country("Sudan", "Khartoum", listOf("Khartum"), "🇸🇩", "Africa"),
        Country("Suriname", "Paramaribo", emptyList(), "🇸🇷", "South America"),
        Country("Sweden", "Stockholm", emptyList(), "🇸🇪", "Europe"),
        Country("Switzerland", "Bern", emptyList(), "🇨🇭", "Europe"),
        Country("Syria", "Damascus", listOf("Damaskus"), "🇸🇾", "Asia"),
        Country("Taiwan", "Taipei", listOf("Taipeh"), "🇹🇼", "Asia"),
        Country("Tajikistan", "Dushanbe", listOf("Duschanbe"), "🇹🇯", "Asia"),
        Country("Tanzania", "Dodoma", listOf("Dar es Salaam"), "🇹🇿", "Africa"),
        Country("Thailand", "Bangkok", listOf("Krung Thep"), "🇹🇭", "Asia"),
        Country("Timor-Leste", "Dili", emptyList(), "🇹🇱", "Asia"),
        Country("Togo", "Lomé", listOf("Lome"), "🇹🇬", "Africa"),
        Country("Tonga", "Nukuʻalofa", listOf("Nuku'alofa", "Nukualofa"), "🇹🇴", "Oceania"),
        Country("Trinidad and Tobago", "Port of Spain", listOf("Port-of-Spain"), "🇹🇹", "North America"),
        Country("Tunisia", "Tunis", emptyList(), "🇹🇳", "Africa"),
        Country("Turkey", "Ankara", emptyList(), "🇹🇷", "Asia"),
        Country("Turkmenistan", "Ashgabat", listOf("Aschgabat"), "🇹🇲", "Asia"),
        Country("Tuvalu", "Funafuti", emptyList(), "🇹🇻", "Oceania"),
        Country("Uganda", "Kampala", emptyList(), "🇺🇬", "Africa"),
        Country("Ukraine", "Kyiv", listOf("Kiew", "Kiev"), "🇺🇦", "Europe"),
        Country("United Arab Emirates", "Abu Dhabi", listOf("Abu-Dhabi"), "🇦🇪", "Asia"),
        Country("United Kingdom", "London", emptyList(), "🇬🇧", "Europe"),
        Country("United States", "Washington, D.C.", listOf("Washington DC", "Washington"), "🇺🇸", "North America"),
        Country("Uruguay", "Montevideo", emptyList(), "🇺🇾", "South America"),
        Country("Uzbekistan", "Tashkent", listOf("Taschkent"), "🇺🇿", "Asia"),
        Country("Vanuatu", "Port Vila", emptyList(), "🇻🇺", "Oceania"),
        Country("Vatican City", "Vatican City", listOf("Vatikanstadt", "Vatikan"), "🇻🇦", "Europe"),
        Country("Venezuela", "Caracas", emptyList(), "🇻🇪", "South America"),
        Country("Vietnam", "Hanoi", emptyList(), "🇻🇳", "Asia"),
        Country("Yemen", "Sana'a", listOf("Sanaa"), "🇾🇪", "Asia"),
        Country("Zambia", "Lusaka", emptyList(), "🇿🇲", "Africa"),
        Country("Zimbabwe", "Harare", emptyList(), "🇿🇼", "Africa")
    )
}
